name: crossy-toad
version: 0.1.0.0
synopsis: A game where you guide a toad across a road.
description: See README
author: Jake Woods
maintainer: jake@jakewoods.net
category: Game

ghc-options:
  -Wall
  -Werror
  -Wcompat
  -Wincomplete-record-updates
  -Wincomplete-uni-patterns
  -Wredundant-constraints
  -O2

default-extensions:
  - FlexibleContexts
  - GeneralizedNewtypeDeriving
  - OverloadedStrings
  - NamedFieldPuns
  - MultiParamTypeClasses
  - DuplicateRecordFields
  - TypeSynonymInstances
  - TypeOperators
  - FlexibleInstances
  - ScopedTypeVariables
  - DataKinds
  - KindSignatures

dependencies:
  - base >=4.9 && <4.12
  - sdl2
  - sdl2-ttf
  - sdl2-image
  - linear
  - mtl
  - transformers
  - lens
  - containers
  - text
  - zippers

library:
  source-dirs: src
  exposed-modules:
    - Game
  ghc-options:
    -fprof-auto-exported

executables:
  crossy-toad:
    main: Main.hs
    source-dirs: executable
    dependencies:
      - crossy-toad

  crossy-toad-prof:
    main: Main.hs
    source-dirs: executable
    dependencies:
      - crossy-toad
    ghc-options:
      -rtsopts
      -threaded
      -fprof-auto-top
      "-with-rtsopts=-N -p -s -h -i0.1"

tests:
  spec:
    main: Driver.hs
    source-dirs:
      - test
      - src
    dependencies:
      - tasty
      - tasty-discover
      - tasty-hspec
      - hspec
      - tasty-hedgehog
      - hedgehog
